---
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - environments/dev

pr: none

variables:
  environment: 'dev'
  ado_service_connection: # add service connection name
  ado_agent_pool: # add agent pool name

jobs:
- template: templates/terragrunt-plan-apply.yml
  parameters:
    environment: $(environment)
    module: applications
    subscription: $(ado_service_connection)
    agent_pool: $(ado_agent_pool)
    plan_or_apply: apply

- template: templates/terragrunt-plan-apply.yml
  parameters:
    environment: $(environment)
    module: base
    subscription: $(ado_service_connection)
    agent_pool: $(ado_agent_pool)
    plan_or_apply: apply
